# 開発用
version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hawkes-process
    volumes:
      - './:/workspace'
    container_name: hawkes-process
    tty: true
    working_dir: '/workspace'
